# Generated by Django 5.0.14 on 2025-12-09 05:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("doctors", "0001_initial"),
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Queue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "qrcode",
                    models.CharField(
                        blank=True,
                        help_text="String representation of the QR code data",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "qrcode_image",
                    models.ImageField(blank=True, null=True, upload_to="qr_codes/"),
                ),
                ("qrcode_generated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queues",
                        to="doctors.doctor",
                    ),
                ),
            ],
            options={
                "db_table": "queues",
                "ordering": ["-date"],
                "unique_together": {("doctor", "date")},
            },
        ),
        migrations.CreateModel(
            name="PatientQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                ("check_in_time", models.TimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("WAITING", "Waiting"),
                            ("IN_PROGRESS", "In Progress"),
                            ("TERMINATED", "Terminated"),
                            ("EMERGENCY", "Emergency"),
                            ("NO_SHOW", "No Show"),
                        ],
                        default="WAITING",
                        max_length=20,
                    ),
                ),
                ("is_emergency", models.BooleanField(default=False)),
                ("checkedin_via_qrcode", models.BooleanField(default=False)),
                (
                    "consultation_start_time",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("consultation_end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "estimated_time",
                    models.IntegerField(
                        default=0, help_text="Estimated wait time in minutes"
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queue_entries",
                        to="patients.patient",
                    ),
                ),
                (
                    "queue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_queues",
                        to="queues.queue",
                    ),
                ),
            ],
            options={
                "db_table": "patient_queues",
                "ordering": ["position"],
                "unique_together": {("queue", "patient")},
            },
        ),
    ]
