# Generated by Django 5.0.14 on 2025-12-11 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PatientForm",
        ),
    ]
