# Generated by Django 5.0.14 on 2025-12-09 05:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="patient_profile",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("address", models.TextField(blank=True)),
                (
                    "emergency_contact",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Emergency contact number must be in the format: '091xxxxxxx', '092xxxxxxx', '093xxxxxxx', or '094xxxxxxx' (10 digits total).",
                                regex="^(091|092|093|094)\\d{7}$",
                            )
                        ],
                    ),
                ),
            ],
            options={
                "db_table": "patients",
            },
        ),
    ]
