# Generated by Django 5.0.14 on 2025-12-11 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chief_complaint",
                    models.TextField(help_text="Main reason for visit"),
                ),
                (
                    "medical_history",
                    models.TextField(blank=True, help_text="Past medical conditions"),
                ),
                (
                    "current_medications",
                    models.TextField(
                        blank=True, help_text="Current medications being taken"
                    ),
                ),
                (
                    "allergies",
                    models.TextField(blank=True, help_text="Known allergies"),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_forms",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "db_table": "patient_forms",
                "ordering": ["-submitted_at"],
            },
        ),
    ]
